name: test remote workflow should stop when python raises an exception

on:
  push:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        uses: nvfp/demo-testing@4.0.0